/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/train-track-bbfcc6c769434911ad704ef42eb4d2fb
Title: Train Track
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Track(props) {
   const { nodes, materials } = useGLTF("models/train_track.glb");
   return (
      <group {...props} dispose={null}>
         <group name="Track_1" position={[0.002, 0.232, 22.545]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh
               name="Object_4"
               castShadow
               receiveShadow
               geometry={nodes.Object_4.geometry}
               material={materials.Track_Rust}
            />
            <mesh
               name="Object_5"
               castShadow
               receiveShadow
               geometry={nodes.Object_5.geometry}
               material={materials.Track_Rust}
            />
            <mesh
               name="Object_6"
               castShadow
               receiveShadow
               geometry={nodes.Object_6.geometry}
               material={materials.Track_Rust}
            />
            <mesh
               name="Object_7"
               castShadow
               receiveShadow
               geometry={nodes.Object_7.geometry}
               material={materials.Track_Rust}
            />
            <mesh
               name="Object_8"
               castShadow
               receiveShadow
               geometry={nodes.Object_8.geometry}
               material={materials.Track_Rust}
            />
            <mesh
               name="Object_9"
               castShadow
               receiveShadow
               geometry={nodes.Object_9.geometry}
               material={materials.Track_Rust}
            />
            <mesh
               name="Object_10"
               castShadow
               receiveShadow
               geometry={nodes.Object_10.geometry}
               material={materials.Track_Silver}
            />
            <mesh
               name="Object_11"
               castShadow
               receiveShadow
               geometry={nodes.Object_11.geometry}
               material={materials.Sleeper}
            />
         </group>
      </group>
   );
}

useGLTF.preload("models/train_track.glb");
