import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Train = forwardRef((props, ref) => {
   const { nodes, materials } = useGLTF("models/teain_model.glb");

   return (
      <group ref={ref} {...props} dispose={null}>
         <group rotation={[-Math.PI / 2, 0, 0]} scale={0.545}>
            <group position={[-1.842, -11.91, -0.072]}>
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_3.geometry}
                  material={materials.Compartmentlambert3SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Compartmentlambert5SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.Compartmentlambert1SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.Compartmentlambert2SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.Compartmentlambert2SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Compartmentlambert2SG}
               />
               <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.Compartmentlambert2SG}
               />
            </group>
         </group>
      </group>
   );
});

useGLTF.preload("models/teain_model.glb");
